Remove overcomplicated check if member was set
Fixes mypy error:
package/test_tools/__private/keys/key_base.py:18: error: Incompatible return value type (got "Optional[str]", expected "str")