Add missing conversion of str to Path in __handle_loading_snapshot
Fixes mypy error:
package/test_tools/__private/node.py:553: error: Argument 1 to "Snapshot" has incompatible type "Union[str, Path]"; expected "Path"