Fix bug with accessing pytest.Package object in fixtures
It turned out, that `request` fixture might not contain required member
and needed information are provided in different location.

```
def __get_pytest_package_object(request) -> Optional[pytest.Package]:
        assert request.scope == 'package'

>       pytest_scope = request.node.items[0]
E       AttributeError: 'Package' object has no attribute 'items'
```