Annotate missing types
Fixes mypy errors:
- Need type annotation for "__unique_names" (hint: "__unique_names: Set[<type>] = ...")
- Need type annotation for "__next_name_numbers" (hint: "__next_name_numbers: Dict[<type>, <type>] = ...")
- package/test_tools/__private/wallet.py:1074: error: Incompatible types in assignment (expression has type "int", variable has type "None")
- package/test_tools/__private/network.py:80: error: Incompatible types in assignment (expression has type "Network", variable has type "None")
- package/test_tools/__private/network.py:82: error: Incompatible types in assignment (expression has type "Network", variable has type "None")
- package/test_tools/__private/wallet.py:1090: error: Incompatible types in assignment (expression has type "TextIOWrapper", variable has type "None")
- package/test_tools/__private/wallet.py:1091: error: Incompatible types in assignment (expression has type "TextIOWrapper", variable has type "None")
- package/test_tools/__private/node.py:690: error: Incompatible types in assignment (expression has type "CleanupPolicy", variable has type "None")
- package/test_tools/__private/wallet.py:1103: error: Incompatible types in assignment (expression has type "Popen[bytes]", variable has type "None")
- package/test_tools/__private/scope/context_definition.py:26: error: Incompatible types in assignment (expression has type "None", variable has type "LoggerWrapper")