Raise exception instead of returning None in __get_pytest_package_object
Fixes mypy errors:
- package/test_tools/__private/scope/scope_fixtures_definitions.py:73: error: Item "None" of "Optional[Package]" has no attribute "name"
- package/test_tools/__private/scope/scope_fixtures_definitions.py:77: error: Item "None" of "Optional[Package]" has no attribute "fspath"